"""
Tiered Context Manager for JARVIS.

Replaces the naive "keep last 3 exchanges, drop the rest" approach with
a production-quality three-tier memory system:

Tier 1 — HOT (in-context window):
    The last N exchange pairs, kept at full fidelity in the messages[] array.
    This is what the LLM sees directly. Same as before, but now when messages
    fall out of this window they get compressed instead of dropped.

Tier 2 — WARM (rolling summary):
    A compressed summary of recent conversation that fell out of Tier 1.
    Generated by asking the LLM to summarize evicted exchanges. Injected
    into the system prompt so the LLM has continuity without full verbatim
    history. Similar to how Claude maintains conversation summaries.

Tier 3 — COLD (vector store):
    Long-term semantic memory via ChromaDB embeddings. Queried via RAG
    before each LLM call — relevant past memories are injected into the
    context. This is the "infinite memory" tier.

Architecture:
    ┌─────────────────────────────────────────────┐
    │  System Prompt                              │
    │  + [WARM] Rolling Summary (compressed)      │
    │  + [COLD] RAG-retrieved relevant memories   │
    ├─────────────────────────────────────────────┤
    │  [HOT] Last N exchange pairs (full text)    │
    ├─────────────────────────────────────────────┤
    │  New user input                             │
    └─────────────────────────────────────────────┘
"""

from typing import Any, Dict, List, Optional

from ..core.logger import get_logger

logger = get_logger(__name__)

# Default rolling summary prompt — asks the LLM to compress evicted messages
_SUMMARIZE_PROMPT = """\
Summarize the following conversation exchanges into a brief paragraph. \
Keep key facts, decisions, user preferences, and action outcomes. \
Drop pleasantries, repeated information, and filler. \
Output ONLY the summary text — no JSON, no preamble.

Exchanges to summarize:
{exchanges}

Previous summary (incorporate and update, don't repeat):
{previous_summary}"""


class ContextManager:
    """
    Three-tier context manager for LLM conversations.

    Sits between the LLM chat interface and the provider, managing what
    context the model actually sees on each turn.
    """

    def __init__(
        self,
        provider: Any,  # BaseLLMProvider
        system_prompt: str,
        hot_window: int = 3,
        contextor: Optional[Any] = None,  # ContextorAdapter with vector store
        rag_top_k: int = 5,
        rag_min_score: float = 0.3,
    ):
        """
        Args:
            provider: LLM provider for summarization calls.
            system_prompt: The base system prompt for this mode.
            hot_window: Number of exchange pairs to keep in Tier 1.
            contextor: ContextorAdapter instance (enables Tier 3 RAG).
            rag_top_k: Number of memories to retrieve per query.
            rag_min_score: Minimum relevance score for RAG results.
        """
        self._provider = provider
        self._system_prompt = system_prompt
        self._hot_window = hot_window
        self._contextor = contextor
        self._rag_top_k = rag_top_k
        self._rag_min_score = rag_min_score

        # Tier 2: Rolling summary of evicted conversations
        self._rolling_summary: str = ""

        # Full exchange history (before trimming) for summarization
        self._all_exchanges: List[Dict[str, str]] = []

        logger.info(
            f"ContextManager: hot_window={hot_window}, "
            f"rag={'enabled' if contextor else 'disabled'}, "
            f"rag_top_k={rag_top_k}"
        )

    @property
    def rolling_summary(self) -> str:
        """Current rolling summary (Tier 2)."""
        return self._rolling_summary

    def build_messages(
        self,
        hot_exchanges: List[Dict[str, str]],
        new_input: str | None = None,
    ) -> List[Dict[str, str]]:
        """
        Build the final messages[] array to send to the LLM.

        Assembles all three tiers into a single message list:
        1. System prompt (augmented with warm summary + RAG context)
        2. Hot exchange pairs (Tier 1)
        3. New user input (if provided)

        Args:
            hot_exchanges: The recent exchange messages (Tier 1).
            new_input: Optional new user message to append.

        Returns:
            Complete messages list ready for provider.chat().
        """
        # --- Build augmented system prompt ---
        system_parts = [self._system_prompt]

        # Tier 2: Inject rolling summary
        if self._rolling_summary:
            system_parts.append(
                f"\n--- CONVERSATION CONTEXT (summary of earlier exchanges) ---\n"
                f"{self._rolling_summary}"
            )

        # Tier 3: RAG retrieval
        if self._contextor and new_input:
            rag_context = self._contextor.retrieve_context(
                query=new_input,
                top_k=self._rag_top_k,
                min_score=self._rag_min_score,
            )
            if rag_context:
                system_parts.append(f"\n--- {rag_context} ---")

        augmented_system = "\n".join(system_parts)

        # --- Assemble final messages ---
        messages: List[Dict[str, str]] = [
            {"role": "system", "content": augmented_system},
        ]
        messages.extend(hot_exchanges)

        if new_input:
            messages.append({"role": "user", "content": new_input})

        return messages

    def compress_evicted(
        self,
        evicted_exchanges: List[Dict[str, str]],
    ) -> None:
        """
        Compress evicted exchanges into the rolling summary (Tier 2).

        Called when messages fall out of the hot window. Instead of
        dropping them, we ask the LLM to summarize them and merge
        the result into the rolling summary.

        Args:
            evicted_exchanges: Messages that were trimmed from Tier 1.
        """
        if not evicted_exchanges:
            return

        # Format evicted exchanges for summarization
        exchange_text = "\n".join(
            f"{msg['role'].upper()}: {msg['content'][:500]}"
            for msg in evicted_exchanges
        )

        prompt = _SUMMARIZE_PROMPT.format(
            exchanges=exchange_text,
            previous_summary=self._rolling_summary or "(none — this is the first summary)",
        )

        try:
            # Use the LLM to generate a compressed summary
            summary = self._provider.chat([
                {"role": "system", "content": "You are a concise summarizer. Output only the summary."},
                {"role": "user", "content": prompt},
            ])

            # Clean up — remove any JSON wrapper the model might add
            summary = summary.strip().strip('"').strip("'")

            if summary and len(summary) > 10:
                self._rolling_summary = summary
                logger.info(
                    f"ContextManager: Compressed {len(evicted_exchanges)} messages "
                    f"into summary ({len(summary)} chars)"
                )
            else:
                logger.warning("ContextManager: Summarization returned empty result")

        except Exception as e:
            logger.warning(f"ContextManager: Summarization failed (non-fatal): {e}")
            # Fallback: simple truncated concatenation
            fallback_parts = []
            if self._rolling_summary:
                fallback_parts.append(self._rolling_summary)
            for msg in evicted_exchanges:
                role = msg["role"]
                content = msg["content"][:200]
                fallback_parts.append(f"{role}: {content}")

            self._rolling_summary = " | ".join(fallback_parts)[-2000:]
            logger.info("ContextManager: Used fallback concatenation for summary")

    def reset(self) -> None:
        """Reset all tiers — full clean slate."""
        self._rolling_summary = ""
        self._all_exchanges.clear()
        logger.debug("ContextManager: Full reset")

    def soft_reset(self) -> None:
        """Reset hot window but keep warm summary and cold store."""
        self._all_exchanges.clear()
        logger.debug("ContextManager: Soft reset (kept summary)")
